# ONLY trigger a build if requested by Travis of awesome repo
if: commit_message = 'Trigger from Awesome Repo'

language: node_js
node_js: "12"
cache:
  directories:
  - node_modules

before_script:
  - npm install
script:
  - npm run modules # fetch the latest modules.yml file from awesome repo
deploy:
  provider: pages
  target_branch: master # Push to master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
