# Don't build if build request was triggered by Travis
if: commit_message != 'Deploy moleculerjs/site to github.com/moleculerjs/site.git:master'

language: node_js
node_js: "12"
cache:
  directories:
  - node_modules

before_script:
  - npm install
script:
  - npm run modules # fetch the latest module file
deploy:
  provider: pages
  target_branch: master # Push to master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
